import type { Salon, Booking } from "./types"

export const mockSalons: Salon[] = [
  {
    id: "salon-1",
    name: "Luxe Hair Studio",
    distance: "0.4 km",
    area: "Downtown",
    stylistCount: 3,
    openNow: true,
    opensAt: "9:00 AM",
    verified: true,
    isLive: true,
    slots: [
      {
        id: "slot-1",
        service: "Haircut & Style",
        time: "2:30 PM",
        price: 65,
        availableIn: "45 min",
        isLastMinute: true,
        slotsLeft: 1,
      },
      {
        id: "slot-2",
        service: "Colour Treatment",
        time: "4:00 PM",
        price: 120,
        availableIn: "2 hrs",
        isLastMinute: false,
        slotsLeft: 2,
      },
    ],
  },
  {
    id: "salon-2",
    name: "North Star Salon",
    distance: "1.1 km",
    area: "Northside",
    stylistCount: 2,
    openNow: true,
    opensAt: "10:00 AM",
    verified: false,
    isLive: true,
    slots: [
      {
        id: "slot-3",
        service: "Blowout",
        time: "3:00 PM",
        price: 45,
        availableIn: "1 hr",
        isLastMinute: true,
        slotsLeft: 1,
      },
    ],
  },
  {
    id: "salon-3",
    name: "Glow Beauty Bar",
    distance: "2.0 km",
    area: "Westside",
    stylistCount: 4,
    openNow: false,
    opensAt: "11:00 AM",
    verified: true,
    isLive: false,
    slots: [],
  },
]

export const mockBookings: Booking[] = [
  {
    id: "booking-1",
    service: "Haircut & Style",
    time: "2:30 PM · Today",
    price: 65,
    deposit: 20,
    customerName: "Alex Johnson",
    status: "pending",
  },
  {
    id: "booking-2",
    service: "Colour Treatment",
    time: "4:00 PM · Tomorrow",
    price: 120,
    deposit: 20,
    customerName: "Alex Johnson",
    status: "confirmed",
  },
  {
    id: "booking-3",
    service: "Blowout",
    time: "10:00 AM · Yesterday",
    price: 45,
    deposit: 20,
    customerName: "Alex Johnson",
    status: "declined",
  },
]
